-- SQL Commands to fix missing deleted_at columns
-- Run these commands in your MySQL database

-- 1. Add deleted_at column to compliance_reports table (if missing)
ALTER TABLE compliance_reports ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;

-- 2. Add deleted_at column to journal_entries table (if missing)
ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;

-- 3. Add deleted_by column to journal_entries table (if missing)
ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS deleted_by INT NULL;

-- 4. Add restored_at column to journal_entries table (if missing)
ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL;

-- 5. Add restored_by column to journal_entries table (if missing)
ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS restored_by INT NULL;

-- 6. Update journal_entries status enum to include 'deleted' (if missing)
ALTER TABLE journal_entries MODIFY COLUMN status ENUM('draft','posted','reversed','voided','deleted') DEFAULT 'draft';

-- 7. Create tax_reports table (if missing)
CREATE TABLE IF NOT EXISTS tax_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    report_type VARCHAR(50) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    generated_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    generated_by INT NOT NULL,
    status ENUM('generating','completed','failed') DEFAULT 'generating',
    file_path VARCHAR(255) NULL,
    report_data JSON NULL,
    tax_amount DECIMAL(18,2) DEFAULT 0.00,
    compliance_score DECIMAL(5,2) DEFAULT 0.00,
    issues_found TEXT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    FOREIGN KEY (generated_by) REFERENCES users(id)
);

-- 8. Create report_settings table (if missing)
CREATE TABLE IF NOT EXISTS report_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    setting_type ENUM('string','number','boolean','json') DEFAULT 'string',
    description TEXT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 9. Insert default report settings (if missing)
INSERT IGNORE INTO report_settings (setting_key, setting_value, setting_type, description) VALUES 
('default_period', 'Monthly', 'string', 'Default report period'),
('default_format', 'PDF', 'string', 'Default report format'),
('company_name', 'Evergreen Accounting & Finance', 'string', 'Company name for reports'),
('fiscal_year_end', '2025-12-31', 'string', 'Fiscal year end date'),
('footer_text', 'This report was generated by Evergreen Accounting System', 'string', 'Custom footer text'),
('auto_monthly', 'true', 'boolean', 'Enable monthly automated reports'),
('auto_quarterly', 'false', 'boolean', 'Enable quarterly automated reports'),
('auto_yearend', 'true', 'boolean', 'Enable year-end automated reports');

-- 10. Verify the changes
SELECT 'compliance_reports' as table_name, COUNT(*) as deleted_at_exists FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'accounting_finance' AND TABLE_NAME = 'compliance_reports' AND COLUMN_NAME = 'deleted_at'
UNION ALL
SELECT 'journal_entries' as table_name, COUNT(*) as deleted_at_exists FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'accounting_finance' AND TABLE_NAME = 'journal_entries' AND COLUMN_NAME = 'deleted_at'
UNION ALL
SELECT 'tax_reports' as table_name, COUNT(*) as table_exists FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'accounting_finance' AND TABLE_NAME = 'tax_reports'
UNION ALL
SELECT 'report_settings' as table_name, COUNT(*) as table_exists FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'accounting_finance' AND TABLE_NAME = 'report_settings';
